### ISSUE TITLE
cond() gives strange results

### ISSUE THREAD

**Issue by sverek** [JuliaMath/DoubleFloats.jl#149] opened 2022-05-11 16:07 UTC
MWE:
```julia
using LinearAlgebra
using GenericLinearAlgebra
using DoubleFloats

n=64
setprecision(BigFloat,1024)
c=Complex{BigFloat}(3//1+1im//1)
M=diagm(1=>c*ones(BigFloat,n-1),-1=>c*ones(BigFloat,n-1),-2=>ones(BigFloat,n-2))

julia> cond(M)
54.8074138822964454124380801523362117312577236107044370350796365017483432382025173214312237494407818341933720310632792243195429135578892101650915175320168929766952853833397539648311643468715429699537481535853705922349050005212852017201765879123675133516677681958832479505953200736998318147420090304082607863538

julia> cond(Complex{Float64}.(M))
54.80741388229623

julia> cond(Complex{Double64}.(M))
2.3353642639886494
```

**Comment by JeffreySarnoff** [comment] 2022-05-12 21:53
Fair point.  I do not know what is happening beyond the fact that there is no special handling of `cond` within 
DoubleFloats.  If you have any additional insight, do share.

**Comment by RalphAS** [comment] 2022-05-12 22:44
Looks like an oversight in the SVD implementation in GenericLinearAlgebra.

For comparison (since you made GenericLinearAlgebra a dependency, I jump through some ugly hoops):
```julia
julia-1.7> extrema(GenericSVD.generic_svdvals!(Complex{Double64}.(M))) |> x-> x[2]/x[1]
54.807413882296444
```

**Comment by JeffreySarnoff** [comment] 2022-05-12 23:17
I had made GenericLinearAlgebra a dependency because (at least then) it was necessary to getting some LinearAlgebra functions to work properly -- is this no longer the case??

**Comment by RalphAS** [comment] 2022-05-13 02:19
Some supplement to the standard libs is still needed. Your current arrangement is probably the best choice for the time being, but the subtext of the GenericLinearAlgebra README is clear: use at your own risk For now I'm just trying to deflect the blame for this issue away from DoubleFloats.

**Comment by JeffreySarnoff** [comment] 2022-05-13 05:20
Thank you!

**Comment by andreasnoack** [comment] 2022-05-13 06:38
It's pretty odd that `GenericLinearAlgebra.svdvals` works fine for `Complex{BigFloat}`, though. I'm trying to figure out what is going on here.

**Comment by andreasnoack** [comment] 2022-05-13 06:59
So it looks like this is caused by the same bug that caused https://github.com/JuliaLinearAlgebra/GenericLinearAlgebra.jl/issues/81. The bug was identified very recently in https://github.com/JuliaLinearAlgebra/GenericLinearAlgebra.jl/issues/81#issuecomment-1125082565 and I have fixed it in https://github.com/JuliaLinearAlgebra/GenericLinearAlgebra.jl/pull/88 which includes the example here as a test case.

**Comment by JeffreySarnoff** [comment] 2022-05-13 07:12
nice work -- will update accordingly

**Comment by andreasnoack** [comment] 2022-05-13 07:12
Closed by https://github.com/JuliaRegistries/General/pull/60158

**Closed by andreasnoack** 2022-05-13 07:12 UTC

**Comment by KlausC** [comment] 2022-05-22 12:11
Please re-open this issue:
The root cause seems to be in `DoubleFloats`:

```
julia> Double64(1e300)^2
NaN

julia> Float64(1e300)^2
Inf
```

**Comment by JeffreySarnoff** [comment] 2022-05-22 18:27
I will address this in the issue you opened.  Thank you, Klaus.

**Comment by andreasnoack** [comment] 2022-05-23 11:47
@KlausC I'm curious how this bug is related to the original issue with the singular values.

**Comment by KlausC** [comment] 2022-05-23 12:36
@andreasnoack I digged that out (as far as I remember):

In [`estimate_σ⁻`](https://github.com/JuliaLinearAlgebra/GenericLinearAlgebra.jl/blob/d16065d74e18b2633e8479cb9a9928f1e786300f/src/svd.jl#L106) `B1` evaluates to `NaN` instead of `Inf` due to the bug in `Double64`; so does the return value.
In [`__svd!`](https://github.com/JuliaLinearAlgebra/GenericLinearAlgebra.jl/blob/d16065d74e18b2633e8479cb9a9928f1e786300f/src/svd.jl#L138) the threshold value now becomes `NaN` too, which spoils up the algorithm effectively, because all comparisons involving `threshold` return `false`.

**Comment by JeffreySarnoff** [comment] 2022-05-23 13:19
@andreasnoack We are working to resolve this, see [#151](https://github.com/JuliaMath/DoubleFloats.jl/issues/151)
